# -*- coding: utf-8 -*-
"""ds_schedule_tools.ipynb

Automatically generated by Colab.

Original file is located at
   
"""







x=7
print(x)

import pandas as pd




data = pd.read_excel("studentcourses.xlsx")

df = pd.DataFrame(data)
print(df.head())

import networkx as nx

df.columns = ['م', 'رقم الطالب', 'اسم الطالب','التخصص','رقم المقرر','اسم المقرر','رمز المقرر ','رقم الشعبة']

df.describe()

df.head()

df.drop(df.columns[0], axis=1, inplace=True)

df.head()

df.sort_values(by='رقم الطالب',ascending=True,inplace=True)

df.head()

df.isnull().sum()

print(df.duplicated().sum())

courses=list(set(df['اسم المقرر']))
print(courses)

no_of_students_in_course=dict(df.groupby('اسم المقرر')['رقم الطالب'].nunique())
no_of_students_in_course

import matplotlib.pyplot as plt
!pip install arabic-reshaper python-bidi
import arabic_reshaper
from bidi.algorithm import get_display

# Ensure the text is a string and Reshape the Arabic text and  Apply the reshaping function to each element of the DataFrame
def reshape_arabic(text):   #isinstance()used to verify the type of an object
    reshaped_text = arabic_reshaper.reshape(text)
    return get_display(reshaped_text)

#need to first convert the Index to a Series to use apply()


reshaped_mokrr = [reshape_arabic(course) for course in no_of_students_in_course.keys()]


no_of_students_in_course_values = list(no_of_students_in_course.values())


plt.figure(figsize=(12, 20))
plt.barh(reshaped_mokrr, no_of_students_in_course_values, color='skyblue', edgecolor='black')


plt.title(reshape_arabic('عدد الطلاب في كل مقرر'), fontsize=16)
plt.xlabel(reshape_arabic('المقرر'), fontsize=12)
plt.ylabel(reshape_arabic('عدد الطلاب'), fontsize=12)
plt.xticks(rotation=45)
plt.show()

courses_network=nx.Graph()
courses_network.add_nodes_from(courses)

grouped_df = df.groupby('رقم الطالب')['اسم المقرر'].apply(list).reset_index()    #The apply(list) operation converts each group of courses into a list
grouped_df

list_courselist = grouped_df['اسم المقرر'].tolist()
list_courselist



import itertools

for sublist in list_courselist:
  for cours_combi in itertools.combinations(sublist,2):
    courses_network.add_edge(cours_combi[0],cours_combi[1])

print(courses_network)

import matplotlib.pyplot as plt

graph_fig=plt.figure(figsize=(12,12))
nx.draw_networkx(courses_network,with_labels=False)

course_degrees=dict(courses_network.degree)
max(course_degrees.values())

print(course_degrees)

reshaped_keys = [reshape_arabic(course) for course in course_degrees.keys()]


plt.figure(figsize=(10, 20))
plt.barh(reshaped_keys, course_degrees.values(), color='skyblue', edgecolor='black')

plt.title(reshape_arabic('عدد الطلاب في كل مقرر'), fontsize=16, fontweight='bold')
plt.xlabel(reshape_arabic('المقرر'), fontsize=12)
plt.ylabel(reshape_arabic('عدد الطلاب'), fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.show()

courses_network.number_of_nodes()

import random as rnd

import matplotlib as matplt

c=list(matplt.colors.CSS4_COLORS.keys())
colour_list=rnd.sample(c,104)
colour_list



from datetime import datetime

dates = []
calendar = {}
count=-4    #bec the first friday is at 4th of april
for i in list(range(1,31)):
    count+=1
    if (count % 7 == 0):     #to skip friday every 7 days
      continue
    for j in list(range(8,20,3)):
        date = datetime(2025, 4, i, j, 0)
        dates.append(date)
        calendar[date] = []

print(calendar)

len(calendar)

color_to_date = {col: dates[i] for i, col in enumerate(colour_list)}

print(color_to_date)

print(colour_list)

def greedy_colouring_algorithm(courses_network, colour_list):
  nodes=list(courses_network.nodes())
  rnd.shuffle(nodes)
  coloured_nodes={}
  for node in nodes:
    node_neighbors=list(dict(courses_network[node]).keys())       #This view is an iterable (not a list), but it can be converted into a list.
    forbidden_colours_of_every_node=[]
    for this_neighbor in node_neighbors :
      if this_neighbor in coloured_nodes:
        forbidden_colours_of_every_node.append(coloured_nodes[this_neighbor])
    for colour in colour_list:
      if colour not in forbidden_colours_of_every_node:
        coloured_nodes[node]=colour
        break
  return coloured_nodes

first_colouring_result=greedy_colouring_algorithm(courses_network=courses_network,colour_list=colour_list)
node_color_map = [first_colouring_result.get(node, 'white') for node in courses_network.nodes()]


nx.draw(courses_network, with_labels=False, node_color=node_color_map, font_weight='bold', node_size=80)
plt.show()

pos = nx.spring_layout(courses_network, seed=420)
nx.draw(courses_network, with_labels=False, node_color=node_color_map, font_weight='bold', node_size=80)
plt.show()

def another_greedy_coloring_algorithm(network, colors):
    nodes = list(network.nodes())
    rnd.shuffle(nodes) # step 1 random ordering
    for node in nodes:
        dict_neighbors = dict(network[node])
# gives names of nodes that are neighbors
        nodes_neighbors = list(dict_neighbors.keys())

        forbidden_colors = []
        for neighbor in nodes_neighbors:
            if len(network.nodes.data()[neighbor].keys()) == 0:
                # if the neighbor has no color, proceed
                continue
            else:
                # if the neighbor has a color,
                # this color is forbidden
                forbidden_colors.append(network.nodes.data()[neighbor]['color'])
         # assign the first color
        # that is not forbidden
        for color in colors:
            # step 2: start everytime at the top of the colors,
            # so that the smallest number of colors is used
            if color in forbidden_colors:
                continue
            else:
                # step 3: color one node at the time
                network.nodes[node]['color'] = color
                break
another_greedy_coloring_algorithm(courses_network, colour_list)
colors_nodes = [data['color'] for v, data in courses_network.nodes(data=True)]
nx.draw(courses_network, node_color=colors_nodes, with_labels=False)

len(set(colors_nodes))

number = []
for i in list(range(0,50)):
    another_greedy_coloring_algorithm(courses_network, colour_list)
    colors_nodes = [data['color'] for v, data in courses_network.nodes(data=True)]
    num_col = len(set(colors_nodes))
    number.append(num_col)
number

for v, data in courses_network.nodes(data=True):
    calendar[color_to_date[data['color']]].append(v)
max_number_exams_sync = len(max(list(calendar.values()),key=len))
rooms = ["Room "+str(i) for i in list(range(max_number_exams_sync))]
pd.DataFrame.from_dict(calendar, orient='index', columns=rooms)            #tells pandas that the dictionary keys (dates) should be used as the index of the DataFrame.

!pip install neo4j

from neo4j import GraphDatabase

# 🔁 Replace these with your actual Aura credentials
uri = "neo4j+s://jsnfdnvdxnv.databases.neo4j.io"
user = "neo4j"
password = "hvfcxrxdcjhnnjmmkb"

driver = GraphDatabase.driver(uri, auth=(user, password))

try:
    with driver.session() as session:
        result = session.run("RETURN 'Connected!' AS msg")
        print(result.single()["msg"])
except Exception as e:
    print("❌ Error connecting to Neo4j:", e)
finally:
    driver.close()

from neo4j import GraphDatabase

class GraphToNeo4j:
    def __init__(self, uri, user, password):
        self.driver = GraphDatabase.driver(uri, auth=(user, password))

    def close(self):
        self.driver.close()

    def create_node(self, tx, node_id, color):
        tx.run("""
            MERGE (n:Node {id: $id})
            SET n.color = $color
        """, id=node_id, color=color)

    def create_edge(self, tx, source, target):
        tx.run("""
            MATCH (a:Node {id: $source})
            MATCH (b:Node {id: $target})
            MERGE (a)-[:CONNECTED_TO]->(b)
        """, source=source, target=target)

    def upload_graph(self, graph):
        with self.driver.session() as session:
            for node_id, attrs in graph.nodes(data=True):
                color = attrs.get('color', 'unknown')
                session.execute_write(self.create_node, node_id, color)

            for source, target in graph.edges():
                session.write_transaction(self.create_edge, source, target)

# Connect to Neo4j and upload
db = GraphToNeo4j("neo4j+s://clkdmvjf.databases.neo4j.io", "neo4j", "jjjjjjjjjwdenvjvjntbvudjmsmvnvj")
db.upload_graph(courses_network)
db.close()
